render/pom.xml
render/src/test/java/org/codice/imaging/nitf/render/NitfRendererTest.java

Also adds jacoco coverage for the render module

[IMG-78] Add unit test for new exception.

---

render/src/main/java/org/codice/imaging/nitf/render/UncompressedBlockRenderer.java
render/src/main/java/org/codice/imaging/nitf/render/imagerep/ImageRepresentationHandlerFactory.java

This should cover the most common case, where the IREPBANDn includes R, G and B.
There is additional work required to handle LU, M and just spaces. IMG-90 should remain open
after this commit.

[IMG-90] Add initial render support for MULTI.

---

render/src/main/java/org/codice/imaging/nitf/render/imagemode/BandSequentialImageModeHandler.java
render/src/main/java/org/codice/imaging/nitf/render/imagemode/BaseImageModeHandler.java
render/src/main/java/org/codice/imaging/nitf/render/imagemode/SharedImageModeHandler.java

Removes duplicate null checks, moves more into BaseImageModeHandler.

[IMG-102] Cleanups of duplicate code in render.

---

render/src/main/java/org/codice/imaging/nitf/render/imagerep/Rgb24ImageRepresentationHandler.java

Added missing copyright header

img-97 Rgb24ImageRepresentationHandler.java missing copyright header

---

fluent-api/pom.xml

Also removed a duplicate dependency.

[IMG-125] Add a friendly name for the fluent API module.

---

core/src/main/java/org/codice/imaging/nitf/core/common/CommonSegment.java
core/src/main/java/org/codice/imaging/nitf/core/common/CommonSegmentImpl.java
core/src/main/java/org/codice/imaging/nitf/core/image/ImageBand.java
core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegment.java
core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentFactory.java
core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentImpl.java
core/src/main/java/org/codice/imaging/nitf/core/image/TargetId.java
core/src/main/java/org/codice/imaging/nitf/core/text/TextSegmentFactory.java
core/src/test/java/org/codice/imaging/nitf/core/image/ImageSegmentFactoryTest.java
fluent-api/licenseheader.txt
fluent-api/nb-configuration.xml
fluent-api/src/test/java/org/codice/imaging/nitf/fluent/CreationFlowTest.java

Also includes tests for the associated creation flow, and API / implementation changes
that the tests showed a need for.

[IMG-143] Add factory for image segments.

---

core/src/main/java/org/codice/imaging/nitf/core/dataextension/DataExtensionSegmentImpl.java
fluent-api/src/main/java/org/codice/imaging/nitf/fluent/NitfCreationFlow.java
fluent-api/src/test/java/org/codice/imaging/nitf/fluent/CreationFlowTest.java

This compares segment FileType and parent (file-level) FileType, and
throws an exception if they differ.

[IMG-150] Protect against FileType mismatch.

---

core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentWriter.java
core/src/main/java/org/codice/imaging/nitf/core/image/TargetId.java
core/src/test/java/org/codice/imaging/nitf/core/image/ImageSegmentFactoryTest.java
core/src/test/java/org/codice/imaging/nitf/core/image/TargetIdTest.java
metadata-comparison/src/main/java/org/codice/nitf/metadatacomparison/FileComparer.java

@dcruver per your suggestion on #83.

[IMG-151] Rename text generation method from getAsText() to textValue().

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/MTIRPB_Test.java

[IMG-140] Add support for MTIRPB TRE.

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/EXOPTA_Test.java
core/src/test/java/org/codice/imaging/nitf/core/tre/SECTGA_Test.java

@dcruver Please test where able.

[IMG-136/157] Add SECTGA and EXOPTA TRE parsing support.

---

core/src/main/java/org/codice/imaging/nitf/core/ConfigurableHeapStrategy.java
core/src/main/java/org/codice/imaging/nitf/core/FileBackedHeapStrategy.java
core/src/main/java/org/codice/imaging/nitf/core/HeapStrategy.java
core/src/main/java/org/codice/imaging/nitf/core/InMemoryHeapStrategy.java
fluent-api/pom.xml
fluent-api/src/main/java/org/codice/imaging/nitf/fluent/NitfParserParsingFlow.java
fluent-api/src/main/java/org/codice/imaging/nitf/fluent/NitfSegmentsFlow.java
fluent-api/src/test/java/org/codice/imaging/nitf/fluent/AdditionalTREsTest.java
fluent-api/src/test/java/org/codice/imaging/nitf/fluent/SegmentsFlowTest.java

img-159 - adding method for cleaning up resource in fluent api

---

core/src/main/java/org/codice/imaging/nitf/core/image/ImageCoordinatePair.java
core/src/main/java/org/codice/imaging/nitf/core/image/ImageCoordinatesRepresentation.java
core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegment.java
core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentParser.java
core/src/test/java/org/codice/imaging/nitf/core/image/CoordinateParseTest.java
metadata-comparison/src/main/java/org/codice/nitf/metadatacomparison/FileComparer.java

This updates the image segment parsing to match the (now approved) RFC-NTB-050 change.

[IMG-61] Update ICORDS / IGEOLO handling

---

core/src/main/java/org/codice/imaging/nitf/core/graphic/GraphicSegment.java
core/src/main/java/org/codice/imaging/nitf/core/graphic/GraphicSegmentFactory.java
core/src/main/java/org/codice/imaging/nitf/core/graphic/GraphicSegmentImpl.java
core/src/test/java/org/codice/imaging/nitf/core/graphic/GraphicSegmentFactoryTest.java

This also adds interface API for modifying GraphicSegmentImpl content.

[IMG-144] Add GraphicSegment factory.

---

core/src/main/java/org/codice/imaging/nitf/core/image/ImageMode.java
core/src/test/java/org/codice/imaging/nitf/core/image/ImageModeTest.java

This allows looping over time, as well as block/line/pixel.

[IMG-173] Add extra IMODE values for MIE4NITF.

---

render/src/main/java/org/codice/imaging/nitf/render/NitfRenderer.java

Modified the NitfRenderer to support JPEG2000 rendering if a plugin is found that will
handle JPEG2000 compression.
@bradh 
@kcwire

IMG-22 Add Support for JPEG2000 rendering - basic

---

README.md

[IMG-182] Update README.md for version bump.

---

core/src/main/java/org/codice/imaging/nitf/core/symbol/SymbolSegment.java
core/src/main/java/org/codice/imaging/nitf/core/symbol/SymbolSegmentFactory.java
core/src/main/java/org/codice/imaging/nitf/core/symbol/SymbolSegmentImpl.java
core/src/test/java/org/codice/imaging/nitf/core/symbol/SymbolSegmentFactoryTest.java

Like the label segment factory, unlikely to be used, but there is no other way to create a symbol segment.

[IMG-145] Add symbol segment factory.

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/TMINTA_Test.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/TMINTA.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/TreWrapper.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/TMINTA_WrapTest.java

Includes XML definition, tests, wrapper and wrapper test.

[IMG-165] Implement TMINTA TRE from MIE4NITF.

---

core/src/main/java/org/codice/imaging/nitf/core/tre/TreEntry.java
core/src/main/java/org/codice/imaging/nitf/core/tre/TreParams.java
core/src/main/java/org/codice/imaging/nitf/core/tre/TreParser.java
core/src/main/resources/nitf_spec.xml
core/src/main/xsd/nitf_spec.xsd
core/src/test/java/org/codice/imaging/nitf/core/image/CoordinateParseTest.java
core/src/test/java/org/codice/imaging/nitf/core/tre/ENGRDA_Test.java
core/src/test/java/org/codice/imaging/nitf/core/tre/MIMCSA_Test.java
core/src/test/java/org/codice/imaging/nitf/core/tre/MTIMSA_Test.java
core/src/test/java/org/codice/imaging/nitf/core/tre/PIATGB_Test.java
core/src/test/java/org/codice/imaging/nitf/core/tre/SharedTreTest.java
core/src/test/java/org/codice/imaging/nitf/core/tre/TreTest.java
core/src/test/java/org/codice/imaging/nitf/core/tre/TreTortureTest.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/MTIMSA_WrapTest.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/TMINTA_WrapTest.java

Became a bit more of a refactoring, with some additional tests to improve coverage.

[IMG-184] Fix TRE serialization.

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/CAMSDA_Test.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/CAMSDA.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/CAMSDA_WrapTest.java

This adds the core parsing / serialisation and TRE wrap for reading.

[IMG-164] Add CAMSDA support.

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/MTIMFA_Test.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/MTIMFA.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/MTIMFA_WrapTest.java

Includes core parsing, TRE wrapper and tests.

[IMG-166] Add Motion Imagery File (MTIMFA) TRE support.

---

core/src/main/java/org/codice/imaging/nitf/core/common/TaggedRecordExtensionHandlerImpl.java
core/src/main/java/org/codice/imaging/nitf/core/tre/TreCollection.java
core/src/test/java/org/codice/imaging/nitf/core/tre/TreCollectionTest.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/TreWrapper.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/PIAPEB_WrapTest.java

This also fixed some minor coverage issues and test process.

[IMG-148] Add support for removing TREs.

---

core/src/main/java/org/codice/imaging/nitf/core/image/ImageCategory.java
core/src/test/java/org/codice/imaging/nitf/core/image/ImageCategoryTest.java

Basically everything gets a .M on the end.
Some of these are impractical / unusable, but they are per MIE4NITF 1.1 Section 5.9.4.2.

[IMG-171] Add ICAT enumeration values for MIE4NITF.

---

core/src/main/java/org/codice/imaging/nitf/core/common/TaggedRecordExtensionHandlerImpl.java
core/src/main/java/org/codice/imaging/nitf/core/tre/TreEntry.java
core/src/main/java/org/codice/imaging/nitf/core/tre/TreGroupImpl.java
core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/Nitf21HeaderTest.java
core/src/test/java/org/codice/imaging/nitf/core/common/TaggedRecordExtensionHandlerTest.java
core/src/test/java/org/codice/imaging/nitf/core/tre/HISTOA_Test.java

Also updates the HISTOA format to support subsequent writing, and adds a test.

[IMG-201/200] Update TRE handling to avoid NPE for missing integer type.

---

registryparser/src/main/java/org/codice/imaging/nitf/registryparser/WorkBook.java
trewrap/pom.xml
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/fields/ACFTBMissionPlanMode.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/fields/ACFTBSceneSource.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/fields/ACFTBSensorId.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/fields/SensorLookup.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/fields/SimpleLookup.java

Several classes were loading files using Class.getResourceAsStream() but they weren't closing
those streams reliably.  This change modifies those classes to guarantee that the InputStreams
will be closed.
@bradh 
@kcwire

IMG-207 changes to guarantee that inputstreams will be closed.

---

trewrap/src/main/java/org/codice/imaging/nitf/trewrap/TreWrapper.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/fields/SensorLookup.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/fields/SimpleLookup.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/ACFTB_WrapTest.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/PIAPEB_WrapTest.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/fields/SensorLookupTest.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/fields/SimpleLookupTest.java

This may conflict with IMG-207 changes, so those should be merged first.

[IMG-209] Initial work on improving tests for TRE wrap.

---

metadata-comparison/src/main/java/org/codice/nitf/metadatacomparison/FileComparer.java

This should never be a problem, but solves IA issue and doesn't hurt.
Patch by John Main, I just formatted it.

[IMG-212] Validate input in file comparer.

---

core/pom.xml
core/src/main/java/org/codice/imaging/nitf/core/image/CoordinateUtility.java
core/src/main/java/org/codice/imaging/nitf/core/image/ImageCoordinatePair.java
core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/SENSRA_Test.java

Updated image coordinate handling to parse and interpret UTM and MGRS coordinates. This PR should not be merged until after usng4j 0.1 has been released.
@bradh

IMG 216 - Modify UTM/MGRS coordinates to return the correct lat/lon

---

core/pom.xml
registryparser/pom.xml
shared-test-resources/pom.xml

A little bit of gratuitous reformatting.

[IMG-223] Fix maven POM problems from IntelliJ reports.

---

core/src/main/java/org/codice/imaging/nitf/core/common/impl/NitfInputStreamReader.java
core/src/test/java/org/codice/imaging/nitf/core/common/impl/NitfInputStreamReaderTest.java

The method NitfInputStreamReader::skip can enter an infinite loop if the input stream has no more bytes to read. This situation can be caused by a corrupt Nitf.
Related JIRA ticket: [IMG-246](https://codice.atlassian.net/browse/IMG-246)

[IMG-246] Fixed NitfInputStreamReader infinite loop

---

.gitignore
core/src/main/java/org/codice/imaging/nitf/core/tre/impl/TreEntryImpl.java
core/src/main/java/org/codice/imaging/nitf/core/tre/impl/TreGroupImpl.java
core/src/main/java/org/codice/imaging/nitf/core/tre/impl/TreParser.java
core/src/main/resources/nitf_spec.xml
core/src/main/xsd/nitf_spec.xsd
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/BANDSB_Test.java
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/TreParser_Test.java
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/TreTortureTest.java

This TRE has some different data encoding, so there are some changes to the parsing logic. That should be generic enough to be useful for other TREs in the future.

BANDSB TRE support

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/SECURA_Test.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/SECURA.java
trewrap/src/main/java/org/codice/imaging/nitf/trewrap/ValidityResult.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/SECURA_WrapTest.java
trewrap/src/test/java/org/codice/imaging/nitf/trewrap/SharedTreTestSupport.java

* Added SECURA to  nitf_spec.xml
* Added SECURA wrapper
* Added tests.
* Updated SharedTreTestSupport to allow for input of a byte array

Update to add SECURA

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/MATESA_Test.java

This is based on the Spectral NITF Implementation Profile Reference Implementation Product Ver 1B.

tre: implement MATESA TRE

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/GRDPSB_Test.java

GRDPSB is from STDI-0002 Appendix P. This is part of the SNIP work.

tre: add GRDPSB TRE

---

core/src/main/resources/nitf_spec.xml
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/ACCHZB_Test.java
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/ACCVTB_Test.java

Implementation from STDI-0002-1 Appendix P.
Test cases from SNIP RIP.

tre: implement ACCHZB and ACCVTB

---

cgm/pom.xml
core-api/pom.xml
core/pom.xml
deswrap/pom.xml
fluent-api/pom.xml
fluent/pom.xml
imagecompare/pom.xml
metadata-comparison/pom.xml
pom.xml
registryparser/pom.xml
render/pom.xml
shared-test-resources/pom.xml
trewrap/pom.xml

This PR is reverting commits that were created by testing. These changes are not functional, but were part of release testing functionality, affecting version numbers and does not affect code.
@bradh 
@mcalcote

Reverting commits created by testing

---

core/src/test/java/org/codice/imaging/nitf/core/BasicWriterTest.java
core/src/test/java/org/codice/imaging/nitf/core/tre/impl/CMETAA_Test.java

Running the tests left three files in the project. Git sees them and treats them as un-added files. This PR uses temp files so the test output is cleaned up.
Here is a screen shot of what was left hanging around after running tests.

Clean up test files
