codice/imaging-nitf

.travis.yml
=> Remove Oracle JDK 7 and OpenJDK 7 from Travis CI.

core/src/main/java/org/codice/imaging/nitf/core/NitfConstants.java, core/src/main/java/org/codice/imaging/nitf/core/SlottedNitfParseStrategy.java, core/src/main/java/org/codice/imaging/nitf/core/label/LabelSegmentHeaderParser.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextConstants.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextDataExtractionParseStrategy.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextFormat.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextSegmentHeader.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextSegmentHeaderImpl.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextSegmentHeaderParser.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf20HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf20OverflowTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21SorcerTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21TextParsingTest.java, nitfNetbeansFileType/src/main/java/org/codice/imaging/nitf/nitfnetbeansfiletype/DeferredSegmentParseStrategy.java, nitfNetbeansFileType/src/main/java/org/codice/imaging/nitf/nitfnetbeansfiletype/NitfTextSegmentNode.java
This change introduces the org.codice.nitf.imaging.core.text package and moves
the TextHeaderSegment and related classes into it.
@bradh 
@kcwire
=> img-58 Repackage text classes

core/src/main/java/org/codice/imaging/nitf/core/image/NitfImageSegmentHeader.java, core/src/main/java/org/codice/imaging/nitf/core/image/NitfImageSegmentHeaderImpl.java, core/src/main/java/org/codice/imaging/nitf/core/image/NitfImageSegmentHeaderParser.java, core/src/main/java/org/codice/imaging/nitf/core/image/PixelJustification.java, core/src/main/java/org/codice/imaging/nitf/core/image/PixelValueType.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf20HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf20OverflowTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21SorcerTest.java, core/src/test/java/org/codice/imaging/nitf/core/image/Nitf21ImageParsingTest.java, core/src/test/java/org/codice/imaging/nitf/core/image/NitfImageSegmentHeaderParserTest.java, render/src/main/java/org/codice/imaging/nitf/render/UncompressedBlockRenderer.java
This is left-over scope from IMG-54.
@dcruver Can you check that this is consistent with your refactoring intent?
=> [IMG-54] Move PixelValueType and PixelJustification enums to image package

nitfNetbeansFileType/pom.xml, render/pom.xml
Changed the name in both affected pom.xml files.
@bradh
@kcwire
=> img-80 render module name uses nitf-imaging instead of imaging-nitf.

cgm/src/test/java/org/codice/imaging/cgm/CgmParserTest.java, render/src/test/java/org/codice/imaging/nitf/render/RenderJitcTest.java
Modified the test classes so the output goes to the target/ folder.
@kcwire 
@bradh
=> img-83 Test output shouldn't write to module folders.

render/src/main/java/org/codice/imaging/nitf/render/ImageMask.java, render/src/main/java/org/codice/imaging/nitf/render/NitfRenderer.java, render/src/main/java/org/codice/imaging/nitf/render/imagehandler/BandSequentialImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagehandler/ImageBlock.java, render/src/main/java/org/codice/imaging/nitf/render/imagehandler/ImageBlockMatrix.java, render/src/main/java/org/codice/imaging/nitf/render/imagehandler/ImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagehandler/ImageRepresentationHandler.java
This change adds support for RGB24:BANDSEQUENTIAL encoded images by adding a new layer of abstraction to the rendering library.
It introduces the concept of an ImageModeHandler, which encapsulates the algorithm necessary for parsing the image data while
delegating the creation of individual pixels to an ImageRepresentationHandler. Future refactoring changes will retrofit existing
imaging rending code into this pattern.
=> img-73 Add support for RGB24:BANDSEQUENTIAL encoded images.

cgm/src/main/java/org/codice/imaging/cgm/CgmIdentifier.java, cgm/src/main/java/org/codice/imaging/cgm/CgmInputReader.java, cgm/src/main/java/org/codice/imaging/cgm/CgmParser.java, cgm/src/main/java/org/codice/imaging/cgm/InteriorStyleElement.java, cgm/src/main/java/org/codice/imaging/cgm/MarkerSizeSpecificationModeElement.java, cgm/src/main/java/org/codice/imaging/cgm/NoArgumentsElement.java, cgm/src/main/java/org/codice/imaging/cgm/PolygonSetElement.java, cgm/src/test/java/org/codice/imaging/cgm/CgmParserTest.java, core/src/main/java/org/codice/imaging/nitf/core/SlottedNitfParseStrategy.java, core/src/main/java/org/codice/imaging/nitf/core/common/AbstractNitfSegmentParser.java, core/src/main/java/org/codice/imaging/nitf/core/image/RasterProductFormatAttributeParser.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/common/AbstractParserTest.java, metadata-comparison/src/main/java/org/codice/nitf/metadatacomparison/FileComparer.java, metadata-comparison/src/main/java/org/codice/nitf/metadatacomparison/FileComparison.java, nitfNetbeansFileType/src/main/java/org/codice/imaging/nitf/nitfnetbeansfiletype/NitfDataObject.java, pom.xml, render/src/main/java/org/codice/imaging/nitf/render/ImageMask.java, render/src/main/java/org/codice/imaging/nitf/render/UncompressedBlockRenderer.java, render/src/main/java/org/codice/imaging/nitf/render/VectorQuantizationBlockRenderer.java, render/src/main/java/org/codice/imaging/nitf/render/flow/package-info.java, render/src/test/java/org/codice/imaging/nitf/render/RenderJitcTest.java
Replaced calls to System.out.println() and Exception.printStackTrace() with logging statements.
@bradh 
@kcwire
=> img-79 Replace all instances of System.out.println() with logging

render/src/main/java/org/codice/imaging/nitf/render/NitfRenderer.java, render/src/main/java/org/codice/imaging/nitf/render/UncompressedBlockRenderer.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/BlockInterleveImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/PixelInterleveImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/RowInterleveImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/SharedImageModeHandler.java
These share a mostly common implementation (because its really all just variation on how data is
arranged within a block).
Removes the RGB support from UncompressedBlockRenderer, since it is now all handled in the new API.
@dcruver
=> [IMG-89] Implement image handler for Pixel, Row and Block Interleve.

render/src/main/java/org/codice/imaging/nitf/render/imagemode/BandSequentialImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/BaseImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/SharedImageModeHandler.java
added 'BaseImageModeHandler' as an abstract class and updated all existing ImageModeHandlers to extend from that.  That class requires the 'getSupportedImageMode()' and 'getHandlerName()' methods and provides the 'checkImageMode' method to subclasses.
@bradh
=> img-99 add 'getSupportedImageMode()' to all ImageModeHandlers

cgm/src/main/java/org/codice/imaging/cgm/CgmInputReader.java, cgm/src/test/java/org/codice/imaging/cgm/CgmInputReaderTest.java
If we don't handle the long text form, it'll break parsing anyway, so an exception is better.
I added a test case, and created a ticket at https://codice.atlassian.net/browse/IMG-98 to explain what the issue really is.
=> [IMG-84] Throw exception instead of logging for an unimplemented text form

render/src/main/java/org/codice/imaging/nitf/render/imagemode/BandSequentialImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/BlockInterleveImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/ImageBlock.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/ImageBlockMatrix.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/PixelInterleveImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/RowInterleveImageModeHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/SharedImageModeHandler.java
This resolves the rendering problem with the v_3301f test case. Unfortunately I don't have a
BANDSEQUENTIAL test case to include, so that is "by analogy".
There is also a simplification of the ImageRepresentationHandler interface.
=> [IMG-71] Implement masking support for each image mode.

cgm/src/test/java/org/codice/imaging/cgm/CgmParserTest.java, core/src/test/java/org/codice/imaging/nitf/core/AbstractWriterTest.java, render/src/test/java/org/codice/imaging/nitf/render/RenderJitcTest.java
There were two issues - use of File.seperator in resource files, and a missing stream close.
=> [IMG-106] Fix maven build on windows.

README.md, render/src/main/java/org/codice/imaging/nitf/render/flow/NitfSegmentsFlow.java, render/src/main/java/org/codice/imaging/nitf/render/flow/package-info.java, render/src/test/java/org/codice/imaging/nitf/render/RenderTestSupport.java
This change adds methods to the fluent API to handle all of the image segment types.
Also updates the README.md file and package-info.java.
=> img-86 Expand fluent API to allow access to non-image segment types

render/src/main/java/org/codice/imaging/nitf/render/ImageMask.java
Added bounds checks to ImageMask.isMaskedBlock(int, int).
=> img-119 ArrayIndexOutOfBoundsException from ImageMask.

core/src/main/java/org/codice/imaging/nitf/core/NitfFileHeader.java, core/src/main/java/org/codice/imaging/nitf/core/common/CommonBasicSegment.java, core/src/main/java/org/codice/imaging/nitf/core/common/CommonBasicSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/common/CommonSegment.java, core/src/main/java/org/codice/imaging/nitf/core/common/CommonSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/common/TaggedRecordExtensionHandler.java, core/src/main/java/org/codice/imaging/nitf/core/common/TaggedRecordExtensionHandlerImpl.java, core/src/main/java/org/codice/imaging/nitf/core/dataextension/DataExtensionSegment.java, core/src/main/java/org/codice/imaging/nitf/core/dataextension/DataExtensionSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/graphic/GraphicSegment.java, core/src/main/java/org/codice/imaging/nitf/core/graphic/GraphicSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegment.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/label/LabelSegment.java, core/src/main/java/org/codice/imaging/nitf/core/label/LabelSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/symbol/SymbolSegment.java, core/src/main/java/org/codice/imaging/nitf/core/symbol/SymbolSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextSegment.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/tre/TreParser.java, metadata-comparison/src/main/java/org/codice/nitf/metadatacomparison/FileComparer.java, nitfNetbeansFileType/src/main/java/org/codice/imaging/nitf/nitfnetbeansfiletype/AbstractCommonSegmentNode.java, nitfNetbeansFileType/src/main/java/org/codice/imaging/nitf/nitfnetbeansfiletype/AbstractSegmentNode.java, render/src/main/java/org/codice/imaging/nitf/render/flow/NitfSegmentsFlow.java
Updated from original proposal, now uses "CommonBasicSegment" instead of "CommonNonExtensionSegment" for those segments other than Data Extension Segment (DES). Not the greatest naming, but the architecture is cleaner.
I added IMG-120 for the NitfFileHeader interface work.
=> [IMG-117] Correct and simplify the segment inheritance.

.gitignore, core/src/main/resources/nitf_spec.xml, core/src/main/xsd/nitf_spec.xsd, core/src/test/java/org/codice/imaging/nitf/core/tre/ENGRDA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/J2KLRA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/SENSRB_Test.java
Also moves in a couple of other TRE tests into the same test module. This is for
consistency and possibly some future refactoring.
=> [IMG-123] Update the TRE structure for J2KLRA.

core/src/main/java/org/codice/imaging/nitf/core/NitfFileHeaderWriter.java, core/src/main/java/org/codice/imaging/nitf/core/common/AbstractSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/graphic/GraphicSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/label/LabelSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/symbol/SymbolSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/text/TextSegmentWriter.java, core/src/test/java/org/codice/imaging/nitf/core/common/AbstractSegmentWriterTest.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/ImageBlock.java
The logic is that for "normal" strings, we will pad or truncate as needed.
For numbers, we'll zero pad, but if the number is too long to fit, we'll throw an
exception, because that would otherwise result in a (silently) corrupted file.
The exception also applies for strings and byte arrays that are supposed to be of
known length (because that will also result in corrupted file, and likely indicates
an implementation problem.
=> [IMG-122] Protect against over-long string and byte arrays.

core/src/main/java/org/codice/imaging/nitf/core/image/ImageBand.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageBandLUT.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageBandParser.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegment.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentParser.java, core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentWriter.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf20HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf20OverflowTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21SorcerTest.java, core/src/test/java/org/codice/imaging/nitf/core/image/Nitf21ImageParsingTest.java, nitfNetbeansFileType/src/main/java/org/codice/imaging/nitf/nitfnetbeansfiletype/NitfImageSegmentNode.java, render/src/main/java/org/codice/imaging/nitf/render/imagerep/ImageRepresentationHandlerFactory.java
This renames NitfImageBand, NitfImageBandLUT and NitfImageBandParser. The other changes
are to match the refactoring.
=> [IMG-92] Remove Nitf prefix on image classes.

core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/image/TargetId.java, core/src/test/java/org/codice/imaging/nitf/core/image/ImageSegmentFactoryTest.java, core/src/test/java/org/codice/imaging/nitf/core/image/TargetIdTest.java, metadata-comparison/src/main/java/org/codice/nitf/metadatacomparison/FileComparer.java
This required moving away from toString(), to support better checking.
@dcruver
=> [IMG-151] Space pad out TargetId values.

core/src/test/java/org/codice/imaging/nitf/core/FileReaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf20HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/Nitf21HeaderTest.java, core/src/test/java/org/codice/imaging/nitf/core/StreamingModeTest.java
The Java behaviour for a URL (from getResource()) is to percent encode, which breaks file operations.
I've switched to a URI, which doesn't do this.
=> [IMG-152] Fix tests on Windows when parent directory contains a space.

.gitignore, fluent-api/src/main/java/org/codice/imaging/nitf/fluent/NitfParserParsingFlow.java, fluent-api/src/test/java/org/codice/imaging/nitf/fluent/AdditionalTREsTest.java, fluent-api/src/test/resources/jitcid.xml
This is slightly untidy in that we need to add the TRE registration
to the parser, but the fluent API ties parser creation and parsing.
@dcruver this might require some deeper consideration in terms of fluent API.
=> [IMG-156] Extend TRE registration to fluent API.

core/src/main/resources/nitf_spec.xml, core/src/test/java/org/codice/imaging/nitf/core/tre/PIAEQA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/PIAEVA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/PIAPEB_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/PIATGB_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/SharedTreTest.java
These are the TREs we did not have from the image library extensions (STDI-0002 Appendix C) version 3 / CN1.
=> Add parsing support for PIAEQA, PIAEVA, PIAPEB and PIATGB

core/src/main/java/org/codice/imaging/nitf/core/image/ImageCompression.java, core/src/test/java/org/codice/imaging/nitf/core/image/ImageCompressionTest.java
Basically this allows storing motion imagery frames in a single image segment.
=> [IMG-172] Add extra IC values for MIE4NITF.

core/src/main/java/org/codice/imaging/nitf/core/image/ImageSegmentFactory.java, core/src/main/java/org/codice/imaging/nitf/core/label/LabelSegment.java, core/src/main/java/org/codice/imaging/nitf/core/label/LabelSegmentFactory.java, core/src/main/java/org/codice/imaging/nitf/core/label/LabelSegmentImpl.java, core/src/test/java/org/codice/imaging/nitf/core/label/LabelSegmentFactoryTest.java
Unlikely to be used since its a NITF 2.0 feature, but there isn't any other way to create a label segment.
Also fixes a comment in the ImageSegmentFactory that I noted during this work.
=> [IMG-146] Add label segment factory.

core/src/main/java/org/codice/imaging/nitf/core/NitfReaderDefaultImpl.java, core/src/main/java/org/codice/imaging/nitf/core/tre/TreEntry.java, core/src/main/java/org/codice/imaging/nitf/core/tre/TreGroup.java, core/src/main/java/org/codice/imaging/nitf/core/tre/TreGroupImpl.java, core/src/main/java/org/codice/imaging/nitf/core/tre/TreParams.java, core/src/main/java/org/codice/imaging/nitf/core/tre/TreParser.java, core/src/main/resources/nitf_spec.xml, core/src/main/xsd/nitf_spec.xsd, core/src/test/java/org/codice/imaging/nitf/core/tre/ENGRDA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/MTIMSA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/SharedTreTest.java, core/src/test/java/org/codice/imaging/nitf/core/tre/TreTest.java, core/src/test/java/org/codice/imaging/nitf/core/tre/TreTortureTest.java, trewrap/src/main/java/org/codice/imaging/nitf/trewrap/FlatTreWrapper.java, trewrap/src/main/java/org/codice/imaging/nitf/trewrap/MTIMSA.java, trewrap/src/main/java/org/codice/imaging/nitf/trewrap/PIAPEB.java, trewrap/src/main/java/org/codice/imaging/nitf/trewrap/TreWrapper.java, trewrap/src/test/java/org/codice/imaging/nitf/trewrap/MTIMSA_WrapTest.java, trewrap/src/test/java/org/codice/imaging/nitf/trewrap/SharedTreTestSupport.java
This extends the parser to handle unsigned integer (big endian) binary as "UINT", for
whatever the specified length is.
=> [IMG-168] Implement MTIMSA, part of MIE4NITF.

cgm/pom.xml, fluent-api/pom.xml, render/pom.xml
Also need to use shared test resources for Fluent API, since its no longer embedded.
=> [IMG-188] Avoid embedding shared test resource in CGM and Render.

core/src/main/resources/nitf_spec.xml
Updated the PIAIMC.MEANGSD to be "real" data type instead of integer in order to match with the spec valid values.
Reviewers:
@bradh 
@glenhein
=> IMG-193: Change PIAIMC.MEANGSD to real data type.

render/src/main/java/org/codice/imaging/nitf/render/imagerep/AbstractRgbImageRepresentationHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagerep/ImageRepresentationHandlerFactory.java, render/src/main/java/org/codice/imaging/nitf/render/imagerep/Rgb24ImageRepresentationHandler.java, render/src/main/java/org/codice/imaging/nitf/render/imagerep/Rgb48ImageRepresentationHandler.java
This fixes the pixel renderer to handle more than 8 bits per pixel per band. Exceptions were being thrown by particular uncompressed images and not being handled correctly.
Reviewers:
@dcruver @bradh
=> [IMG-194]: Fixed the RGB image handler to handle 16 bitsPerPixelPerBand for uncompressed images.

fluent-api/src/main/java/org/codice/imaging/nitf/fluent/NitfParserParsingFlow.java
Defaulted the NitfParserParsingFlow to use the InMemoryHeapStrategy. This strategy is faster than the FileBackedHeapStrategy that uses the RandomAccessFile and the rendering of a BufferedImage is the driving factor on how much memory is used during rendering.
Ticket:
https://codice.atlassian.net/browse/IMG-199
Reviewers:
@dcruver @jlcsmith @bradh
=> Default to InMemoryHeapStrategy as BufferedImages are rendered in memory

core/src/main/resources/nitf_spec.xml, core/src/test/java/org/codice/imaging/nitf/core/tre/ENGRDA_Test.java
The previous implementation did not handle data size correctly, always assuming it to be 1.
=> [IMG-197] - Correct ENGRDA handling.

core/src/main/java/org/codice/imaging/nitf/core/header/NitfHeader.java
Add a setComplexityLevel to NitfHeader so that the default value of "3" can be overridden when writing a NITF. NitfHeaderImpl already has the method, so this is just an addition to the interface.
Reviewers:
@bradh 
@dcruver 
@kcwire 
https://codice.atlassian.net/browse/IMG-204
=> IMG-204 add setComplexityLevel to NitfHeader

core/src/main/java/org/codice/imaging/nitf/core/common/NitfInputStreamReader.java, core/src/test/java/org/codice/imaging/nitf/core/common/NitfInputStreamReaderTest.java
It is possible for the NitfInputStreamReader to ask for all the bytes of an input stream, but only get back a partial amount an then throw a NitfFormatException. This happens where the stream content is still being written to and it is not all available to be read.
Ticket: https://codice.atlassian.net/browse/IMG-206
Reviewers:
@dcruver 
@bradh
=> IMG-206: Update NitfInputStream to handle partial reads of streams

core/src/main/java/org/codice/imaging/nitf/core/SlottedParseStrategy.java, core/src/main/java/org/codice/imaging/nitf/core/common/AbstractSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/dataextension/DataExtensionSegment.java, core/src/main/java/org/codice/imaging/nitf/core/dataextension/DataExtensionSegmentFactory.java, core/src/main/java/org/codice/imaging/nitf/core/dataextension/DataExtensionSegmentImpl.java, core/src/main/java/org/codice/imaging/nitf/core/dataextension/DataExtensionSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/dataextension/UserDefinedDataExtensionSegment.java, deswrap/src/main/java/org/codice/imaging/nitf/deswrap/CSSHPA.java, deswrap/src/main/java/org/codice/imaging/nitf/deswrap/CSSHPAUserDefinedDES.java, deswrap/src/test/java/org/codice/imaging/nitf/deswrap/CSSHPA_CreateTest.java
Previously a FileImageOutputStream in CSSHPAUserDefinedDES: getUserData(), wasn't getting closed after being used. This PR will guarantee that the stream will always get closed after it's use. Also, the temp file that gets created as an input to the stream will get deleted at the same time the stream closes.
@dcruver 
@bradh
=> IMG-207 Guarantee input stream will be closed to prevent resource leaks

imagecompare/src/main/java/org/codice/imaging/compare/Compare.java, render/src/main/java/org/codice/imaging/nitf/render/NitfRenderer.java, render/src/main/java/org/codice/imaging/nitf/render/imagemode/BandSequentialImageModeHandler.java, render/src/test/java/org/codice/imaging/nitf/render/RenderTestSupport.java
Currently, NitfRenderer renders to a BufferedImage that is 32-bit AGRB. This change adds support for NITFs to be rendered to a BufferedImage with the same data model as the original. 
NB: The original code renders to an image that is transparent. The new code renders to an image with a transparency setting equal to the first image block that was decoded. It is unclear at this time which approach is technically correct according to the NITF spec. The ticket IMG-208 was created to research this issue.
Reviewers:
@bradh 
@dcruver 
@jlcsmith
=> IMG-205 Render to original data model

registryparser/src/main/java/org/codice/imaging/nitf/registryparser/WorkBook.java
Not sure the registry parser part of IMG-207 really worth it, because the close() operation is a no-op and the stream lives for as long as main() anyway. Its done though.
=> [IMG-207] Close streams in registry parser

core/src/main/java/org/codice/imaging/nitf/core/tre/impl/TreParser.java, core/src/test/java/org/codice/imaging/nitf/core/tre/impl/TreParser_Test.java
Slightly revised approach - now throws instead of returning 0 for default case (which should not occur unless an item is added to the TreSource enumeration).
=> [IMG-224] Implement check for oversize TREs on write.

core/src/main/java/org/codice/imaging/nitf/core/tre/impl/TreParser.java
I'm reconsidering the proposal that @harrison-tarr made for IMG-225, to protect against possible bad usage via client API.
This PR basically just squashes the previous PR - I have not intended substantive changes.
@harrison-tarr : can you take a quick look to make sure I haven't changed your intent?
=> IMG-225 Add protections for entity expansion

core/src/main/java/org/codice/imaging/nitf/core/common/impl/AbstractSegmentWriter.java, core/src/main/java/org/codice/imaging/nitf/core/tre/impl/TreParser.java, core/src/test/java/org/codice/imaging/nitf/core/tre/impl/PIATGB_Test.java
Allows the writing of blank or null integers and real numbers as spaces to support TREs that allow null numbers to represent unknown values such as the PIATGB TRE's TGTLAT and TGTLON fields.
=> Fix for blank numbers

fluent-api/src/main/java/org/codice/imaging/nitf/fluent/NitfParserInputFlow.java, fluent/src/main/java/org/codice/imaging/nitf/fluent/impl/NitfParserInputFlowImpl.java
This allows for the skip timeout to be configured by clients.
Relates to #193
=> IMG-250 Overloads file() and inputStream() methods of NitfParserInputFlow

registryparser/pom.xml
The (DoS vulnerability) isn't really applicable, since we're working off a trusted source, but no harm in the upgrade here.
=> upgrade Apache POI version

core/pom.xml, pom.xml
Upgrade to compile with Java 11
- Needed to include Jakarta XML bind and jakarta activation api
- Updated the maven compiler plugin (wasn't required but was overdue)
- Verified and tested with the Alliance Java 11 branch downstream https://github.com/codice/alliance/tree/alliance-java11
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/codice/imaging-nitf/218)
=> Upgrade to Java 11

core/src/main/java/org/codice/imaging/nitf/core/security/impl/FileSecurityMetadataBuilder20.java, core/src/main/java/org/codice/imaging/nitf/core/security/impl/FileSecurityMetadataBuilder21.java, core/src/main/java/org/codice/imaging/nitf/core/security/impl/SecurityMetadataBuilder20.java, core/src/main/java/org/codice/imaging/nitf/core/security/impl/SecurityMetadataBuilder21.java, core/src/test/java/org/codice/imaging/nitf/core/security/impl/FileSecurityMetadataBuilderTest.java, core/src/test/java/org/codice/imaging/nitf/core/security/impl/SecurityMetadataBuilderTest.java
This follows on from the main IMG-233 changes to make builders for the security / file security metadata.
=> [IMG-233] Additional Security changes to remove public constructors.

core/pom.xml, core/src/main/java/org/codice/imaging/nitf/core/image/impl/RasterProductFormatUtilities.java, core/src/main/java/org/codice/imaging/nitf/core/tre/impl/TreParser.java, core/src/test/java/org/codice/imaging/nitf/core/tre/impl/BANDSB_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/impl/CCINFA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/impl/ENGRDA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/impl/MTIMSA_Test.java, core/src/test/java/org/codice/imaging/nitf/core/tre/impl/TreTortureTest.java, pom.xml, render/src/test/java/org/codice/imaging/nitf/render/Jpeg2000Test.java, render/src/test/java/org/codice/imaging/nitf/render/JpegTest.java, trewrap/src/test/java/org/codice/imaging/nitf/trewrap/MTIMSA_WrapTest.java
The package `javax.xml.bind` has been replaced with `jakarta.xml.bind` in projects like Spring. This commit updates the dependencies to use the new Jakarta packages.
=> Upgrade to jakarta.xml.bind 4.0
